version: '3.5'

services:
  postgres:
    image: postgres
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=unsafe
      - POSTGRES_DB=workhours
    ports:
      - 5432:5432
    container_name: pg-workhours