name: Rust

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: elgohr/Publish-Docker-Github-Action@2.12
      with:
        name: ajhaa/workhours_bot
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}       
        cache: true # cache builds
